    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: library
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./docker-settings/php-fpm
        expose:
            - "9000"
        volumes:
            - .:/var/www/symfony
            - ./docker-settings/logs/symfony:/var/www/symfony/var/logs
        links:
            - db
    nginx:
        build: ./docker-settings/nginx
        ports:
            - "9000:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker-settings/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./docker-settings/elk/logstash:/etc/logstash
            - ./docker-settings/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx